# Generated by Django 3.1.7 on 2021-03-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
