# Generated by Django 3.1.7 on 2021-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210302_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.IntegerField(choices=[(1, 'Others'), (2, 'Access Control'), (3, 'Carpentry'), (4, 'CCTV'), (5, 'Civil'), (6, 'Electricity'), (7, 'Fire'), (8, 'Horticulture'), (9, 'House Keeping'), (10, 'Masonry'), (11, 'Plumbing')], default=1),
        ),
    ]
