# Generated by Django 3.1.7 on 2021-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210405_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcategories',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
