# Generated by Django 3.1.7 on 2021-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_locationchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reminder',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.IntegerField(choices=[(2, 'Others')], default=1),
        ),
    ]
