# Generated by Django 3.1.7 on 2021-04-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210405_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reminder',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
