# Generated by Django 3.1.7 on 2021-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210405_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reminder',
            field=models.DateTimeField(null=True),
        ),
    ]
