# Generated by Django 3.1.7 on 2021-04-07 01:35

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210405_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='media',
            field=models.FileField(null=True, upload_to=dashboard.models.user_directory_path),
        ),
    ]
