# Generated by Django 3.1.7 on 2021-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_complaint_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='media',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
