# Generated by Django 3.1.7 on 2021-04-07 01:40

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210407_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='media',
            field=models.FileField(null=True, upload_to=dashboard.models.user_directory_path),
        ),
    ]
